# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 635)
        MainWindow.setMinimumSize(QtCore.QSize(973, 635))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(14, 13, 947, 574))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_enableCamera = QtWidgets.QCheckBox(self.widget)
        self.checkBox_enableCamera.setObjectName("checkBox_enableCamera")
        self.verticalLayout_4.addWidget(self.checkBox_enableCamera)
        self.label_Image = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image.sizePolicy().hasHeightForWidth())
        self.label_Image.setSizePolicy(sizePolicy)
        self.label_Image.setMinimumSize(QtCore.QSize(640, 480))
        self.label_Image.setSizeIncrement(QtCore.QSize(1, 1))
        self.label_Image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout_4.addWidget(self.label_Image)
        self.pushButton_confirmArena = QtWidgets.QPushButton(self.widget)
        self.pushButton_confirmArena.setObjectName("pushButton_confirmArena")
        self.verticalLayout_4.addWidget(self.pushButton_confirmArena)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_enableFPS = QtWidgets.QCheckBox(self.widget)
        self.checkBox_enableFPS.setObjectName("checkBox_enableFPS")
        self.horizontalLayout_3.addWidget(self.checkBox_enableFPS)
        self.checkBox_enablePosition = QtWidgets.QCheckBox(self.widget)
        self.checkBox_enablePosition.setObjectName("checkBox_enablePosition")
        self.horizontalLayout_3.addWidget(self.checkBox_enablePosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_activation = QtWidgets.QGroupBox(self.widget)
        self.groupBox_activation.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_activation.setObjectName("groupBox_activation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_activation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_connection = QtWidgets.QGroupBox(self.groupBox_activation)
        self.groupBox_connection.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_connection.setFlat(False)
        self.groupBox_connection.setCheckable(False)
        self.groupBox_connection.setObjectName("groupBox_connection")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_connection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_address = QtWidgets.QLineEdit(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_address.sizePolicy().hasHeightForWidth())
        self.lineEdit_address.setSizePolicy(sizePolicy)
        self.lineEdit_address.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout.addWidget(self.lineEdit_address)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_port.sizePolicy().hasHeightForWidth())
        self.lineEdit_port.setSizePolicy(sizePolicy)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_connection)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_connectionStatus = QtWidgets.QLabel(self.groupBox_connection)
        self.label_connectionStatus.setObjectName("label_connectionStatus")
        self.horizontalLayout_4.addWidget(self.label_connectionStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox_connection)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.groupBox_connection)
        self.checkBox_watchdog = QtWidgets.QCheckBox(self.groupBox_activation)
        self.checkBox_watchdog.setObjectName("checkBox_watchdog")
        self.verticalLayout_2.addWidget(self.checkBox_watchdog)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox_activation)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_2.addWidget(self.pushButton_start)
        self.line_2 = QtWidgets.QFrame(self.groupBox_activation)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_6.addWidget(self.groupBox_activation)
        self.groupBox_mouvments = QtWidgets.QGroupBox(self.widget)
        self.groupBox_mouvments.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_mouvments.setObjectName("groupBox_mouvments")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_mouvments)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_mouvments)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout.addWidget(self.pushButton_up, 0, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.groupBox_mouvments)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox_mouvments)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 1, 1, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.groupBox_mouvments)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_mouvments)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout.addWidget(self.pushButton_down, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.line_3 = QtWidgets.QFrame(self.groupBox_mouvments)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.verticalLayout_6.addWidget(self.groupBox_mouvments)
        self.groupBox_AnswerandBattery = QtWidgets.QGroupBox(self.widget)
        self.groupBox_AnswerandBattery.setObjectName("groupBox_AnswerandBattery")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_AnswerandBattery)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_getBattery = QtWidgets.QCheckBox(self.groupBox_AnswerandBattery)
        self.checkBox_getBattery.setObjectName("checkBox_getBattery")
        self.verticalLayout_5.addWidget(self.checkBox_getBattery)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_AnswerandBattery)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_lastAnswer = QtWidgets.QLabel(self.groupBox_AnswerandBattery)
        self.label_lastAnswer.setObjectName("label_lastAnswer")
        self.horizontalLayout_5.addWidget(self.label_lastAnswer)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_AnswerandBattery)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 22))
        self.menubar.setObjectName("menubar")
        self.menu_Quitter = QtWidgets.QMenu(self.menubar)
        self.menu_Quitter.setObjectName("menu_Quitter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quitter = QtWidgets.QAction(MainWindow)
        self.action_Quitter.setObjectName("action_Quitter")
        self.action_OpenMessageLog = QtWidgets.QAction(MainWindow)
        self.action_OpenMessageLog.setObjectName("action_OpenMessageLog")
        self.menu_Quitter.addAction(self.action_OpenMessageLog)
        self.menu_Quitter.addSeparator()
        self.menu_Quitter.addAction(self.action_Quitter)
        self.menubar.addAction(self.menu_Quitter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Monitor"))
        self.checkBox_enableCamera.setText(_translate("MainWindow", "Enable Ca&mera"))
        self.pushButton_confirmArena.setText(_translate("MainWindow", "Co&nfirme arena border..."))
        self.checkBox_enableFPS.setText(_translate("MainWindow", "Enable &FPS"))
        self.checkBox_enablePosition.setText(_translate("MainWindow", "Enable Pos&ition"))
        self.groupBox_activation.setTitle(_translate("MainWindow", "Robot Activation"))
        self.groupBox_connection.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "Status:"))
        self.label_connectionStatus.setText(_translate("MainWindow", "Not connected"))
        self.checkBox_watchdog.setText(_translate("MainWindow", "Start with &watchdog"))
        self.pushButton_start.setText(_translate("MainWindow", "Start r&obot"))
        self.groupBox_mouvments.setTitle(_translate("MainWindow", "Mouvments"))
        self.pushButton_up.setText(_translate("MainWindow", "&Up"))
        self.pushButton_left.setText(_translate("MainWindow", "&Left"))
        self.pushButton_stop.setText(_translate("MainWindow", "&Stop"))
        self.pushButton_right.setText(_translate("MainWindow", "&Right"))
        self.pushButton_down.setText(_translate("MainWindow", "&Down"))
        self.groupBox_AnswerandBattery.setTitle(_translate("MainWindow", "Others"))
        self.checkBox_getBattery.setText(_translate("MainWindow", "Get &Battery"))
        self.label_4.setText(_translate("MainWindow", "Last answer:"))
        self.label_lastAnswer.setText(_translate("MainWindow", "None"))
        self.menu_Quitter.setTitle(_translate("MainWindow", "M&enu"))
        self.action_Quitter.setText(_translate("MainWindow", "&Quitter"))
        self.action_OpenMessageLog.setText(_translate("MainWindow", "O&pen message log..."))
